### ISSUE TITLE
Suggestion - move opacity to images instead of body or html

### ISSUE THREAD

**Issue by jzhu01** [tommygebru/review-teacozy#1]
Seen here: https://github.com/tommygebru/review-teacozy/blob/8e26d525a733e0f5ef41ea59980ec2d4b4d71eaf/style.css#L13

Since these tend to make it more difficult to view the text against a dark background, I recommend using them only on the images instead. :)

**Comment by tommygebru** [comment]
Hey Jzhu01 thanks for the tip, so i believe that the spec sheet lists this as a general style to the body/html 👍
