### ISSUE TITLE
Suggestion - add links to your nav!

### ISSUE THREAD

**Issue by jzhu01** [tommygebru/review-teacozy#2]
Seen here: https://github.com/tommygebru/review-teacozy/blob/8e26d525a733e0f5ef41ea59980ec2d4b4d71eaf/index.html#L14-L16

It might be nice to try to add some links to your nav! Here's a resource talking more about it: https://www.w3schools.com/tags/att_global_id.asp

**Comment by tommygebru** [comment]
Totally slipped my mind! 😅
