### ISSUE TITLE
Suggestion - create general flex class

### ISSUE THREAD

**Issue by jzhu01** [tommygebru/review-teacozy#3]
Seen here: https://github.com/tommygebru/review-teacozy/blob/8e26d525a733e0f5ef41ea59980ec2d4b4d71eaf/style.css#L46-L48
Since these properties repeat throughout various sections, it might be useful to reduce the repetition and set it once using a general flex class.

**Comment by tommygebru** [comment]
Good eye Jzhu01 💯
