### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [tommygebru/review-teacozy#5]
Fantastic job on this project - I really liked how you styled your header and appreciated your usage of flex properties throughout the code. In terms of improvements, some of the changes I recommend are applying a general flex container throughout the page, adding links to sections in your page in the nav, and moving the opacity from the body to the images.

If you’re in the mood for a challenge, I would look into implementing a mobile version of this page! Here's a link to get you started: https://www.w3schools.com/css/css_rwd_mediaqueries.asp. Keep up the awesome work! ^_^

**Comment by tommygebru** [comment]
I appreciate the feedback, Im surprised there werent more errors because i didnt proof it for the DRY method 😂 
Ok so i made some improvements 👍 Thanks for taking the time to review my project Jzhu01 🎉

**Comment by tommygebru** [comment]
I appreciate the feedback, Im surprised there werent more errors because i didnt proof it for the DRY method 😂 
Ok so i made some improvements 👍 Thanks for taking the time to review my project Jzhu01 🎉
